# Generated by Django 4.2.3 on 2023-07-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
